// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModalMais.Transferencia.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ModalMais.Transferencia.Api.Migrations
{
    [DbContext(typeof(TransferenciaPixContext))]
    [Migration("20210830152253_Transferencia")]
    partial class Transferencia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ModalMais.Transferencia.Api.Entities.TransferenciaPix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chave")
                        .HasColumnType("varchar");

                    b.Property<DateTime>("DataTransferencia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("NumeroBanco")
                        .HasColumnType("varchar");

                    b.Property<string>("NumeroConta")
                        .HasColumnType("varchar");

                    b.Property<string>("Agencia")
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("varchar");

                    b.Property<int>("TipoChave")
                        .HasColumnType("integer");

                    b.Property<double>("Valor")
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id");

                    b.ToTable("Transferencias");
                });
#pragma warning restore 612, 618
        }
    }
}
